services:
  whatsapp-analyser:
    build: .
    image: kaiserruben/whatsapp-analyser:latest
    platform: linux/amd64
    ports:
      - "12345:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1